version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: composer
    directory: ./
    schedule:
      interval: daily
    labels:
      - dependencies
    open-pull-requests-limit: 0 # open Pull Requests for security updates only
